In [7]:
import numpy as np

In [8]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([1,2,3])
print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [9]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[1],[2]])
print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [10]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([1])
print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [11]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([1,2,3,4])
print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [12]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([1,2,3,4])
print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [13]:
arr_1 = np.array([[1],[2],[3],[4],[5]])
arr_2 = np.array([1,2,3,4])
print(arr_1 + arr_2)
arr_1.dot(arr_2.reshape(1,-1))
np.matmul(arr_1, arr_2.reshape(1,-1))

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

# Problem Solving


a. Find the distance between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset and append the newly calculated distances as new column with the given dataset

b. Given any data point, generate 3 closest neighbors from it

In [14]:
# answer of a

In [15]:
# step 1:- generate random data with 1 million rows and columns
df = np.random.rand(1000000,2)
df.shape
print(df)

[[0.34882195 0.4590292 ]
 [0.21484893 0.77832295]
 [0.39685802 0.26565679]
 ...
 [0.98732814 0.82702239]
 [0.97651486 0.9809401 ]
 [0.83112431 0.69632815]]


In [16]:
# step 2:- compute the centroid
centroid = np.mean(df, axis=0)
centroid.shape
centroid

array([0.50030937, 0.5003979 ])

In [17]:
# step 3:- compute the distance of each datapoint from centroid

dist = np.sqrt(np.sum(np.square(df - centroid), axis=1))
# Doing squareroot and
# printing Euclidean distance
print(dist)

[0.15703441 0.39840933 0.25652596 ... 0.58640501 0.67652973 0.38448301]


In [18]:
# appending the dist in 3rd column
arr = np.column_stack((df, dist))
print(arr)

[[0.34882195 0.4590292  0.15703441]
 [0.21484893 0.77832295 0.39840933]
 [0.39685802 0.26565679 0.25652596]
 ...
 [0.98732814 0.82702239 0.58640501]
 [0.97651486 0.9809401  0.67652973]
 [0.83112431 0.69632815 0.38448301]]


In [19]:
# Given any data point, generate 3 closest neighbors from it
# creating the random points lets say 1000*2
df = np.random.rand(1000,2)
# step 2:- compute the centroid
centroid = np.mean(df, axis=0)
# step 3:- compute the distance of each datapoint from centroid
dist = np.sqrt(np.sum(np.square(df - centroid), axis=1))
k = 3
indices = np.argsort(dist)[:k]
neighbors = df[indices]
print("Three closest neighbors to centroid:\n", neighbors)

Three closest neighbors to centroid:
 [[0.49935955 0.48817816]
 [0.49200076 0.50625413]
 [0.48517702 0.47997176]]
